export * from './src/app/modules/spinner/spinner.module'
export * from './src/app/modules/drop-down/drop-down.module'
export * from './src/app/modules/star/star.module'
export * from './src/app/modules/table/table.module'
export * from './src/app/modules/modal/modal.module'
export * from './src/app/directives/directive.module'
export * from './src/app/directives/modal-host'
export { AppModal } from './src/app/modules/modal/modal/modal.component'
export * from './src/app/modules/modal/modal/modal.component'
export * from './src/app/modules/plus/plus.module'
export * from './src/app/modules/bar-graph/bar-graph.module'
export * from './src/app/modules/button/button.module'

